# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: daavril <daavril@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/16 14:47:59 by daavril           #+#    #+#              #
#    Updated: 2024/05/17 21:40:40 by daavril          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = ft_display_file.c \

all : $(NAME)

${NAME} : ${SRC}
	cc -Wall -Wextra -Werror $^ -o $@

clean :
	
fclean : clean
	rm -rf ${NAME}