DOCKER_COMPOSE = docker compose -f srcs/docker-compose.yml

build:
	$(DOCKER_COMPOSE) build

up:
	$(DOCKER_COMPOSE) up

down:
	$(DOCKER_COMPOSE) down

ps:
	$(DOCKER_COMPOSE) ps -a

logs:
	$(DOCKER_COMPOSE) logs -f
